name: Docker CI

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t llama-chatbot-app .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag and Push Docker image
        run: |
          IMAGE="${{ secrets.DOCKER_USERNAME }}/llama-chatbot-app:latest"
          docker tag llama-chatbot-app $IMAGE
          docker push $IMAGE

      - name: List Docker images
        run: docker images
